### ISSUE TITLE
Add Sector 3 Beta v0.3 and Sector 6 Kaizo Beta v0.2.2 & v0.3

### ISSUE THREAD

**Issue by AbyssalCreature** [VanessaMae1087/AM2R-TimeTrials-Level-List#4]
Both levels have been tested and beaten.
Sector 3 is beatable, requires speedboosting knowledge, as well beinSectg aware of _**SpeedCharge "stations",**_ aka, the bug of running against a slope with a block, last version is **v0.3.**
Sector 6 Kaizo has been beaten on both versions, **v0.2.2** requires damage tanking to be beaten; **v0.3** now does require more space jumping and in theory shouldn't be required to damage tank. Both versions require really advanced knowledge of _wall jumping, bomb jumping, spiderball uses, speedboosting, mockball, ballspark, ballboosting, SpeedCharge "Stations",_ etc. 

Two different versions of Sector 6 are uploaded because Druid's petition.
### **NOT MEANT FOR BEGINNERS!!**

Further updates for these levels are planned when the next **_Time Trials update_** launches.
[Levels.zip](https://github.com/VanessaMae1087/AM2R-TimeTrials-Level-List/files/9687023/Levels.zip)

**Comment by VanessaMae1087** [comment]
for future reference, you can create a pull request with any levels you wish to add, or send them in discord DMs, which would be better than opening an issue
