### ISSUE TITLE
Levels aren't in the v0.3+ format

### ISSUE THREAD

**Issue by mayzmae** [VanessaMae1087/AM2R-TimeTrials-Level-List#9]
at the moment most levels in the list are still using the v0.1/v0.2 format. this isn't a problem on it's own since older levels are converted to the newer format upon launching the game, however it would be nice to fix for consistency's sake with any v0.3+ additions

**Comment by Miepee** [comment]
Note: that since most levels are currently in v.0.1/2, this means that all 0.3+ levels will currently fail with the actions build
